<a href="https://colab.research.google.com/github/aaronyu888/mat-494-notebooks/blob/main/Linear_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Chapter 1.3 Linear Regression


---



# 1.3.1 QR Decomposition
QR factorization takes the general form $A = QR$ where $Q$ is the product of the Gram-Schmidt process, and $R$ is an upper triangular matrix.

In [1]:
import numpy as np

In [2]:
A = np.random.randint(10, size = (3, 3))
q, r = np.linalg.qr(A)
print('A: \n', A, '\n')
print('Q: \n', q, '\n')
print('R: \n', r, '\n')

A: 
 [[4 4 2]
 [1 6 4]
 [3 2 7]] 

Q: 
 [[-0.78446454  0.06052275 -0.6172134 ]
 [-0.19611614 -0.96836405  0.15430335]
 [-0.58834841  0.24209101  0.77151675]] 

R: 
 [[-5.09901951 -5.49125178 -6.47183246]
 [ 0.         -5.08391127 -2.05777361]
 [ 0.          0.          4.78340385]] 



In [3]:
p = (np.matmul(q, r))
print(p, '\n')
print(A)


[[4. 4. 2.]
 [1. 6. 4.]
 [3. 2. 7.]] 

[[4 4 2]
 [1 6 4]
 [3 2 7]]


As you can see from the above code, $Q$ dotted with $R$ gives us back $A$.



# 1.3.2 Least-squares Problems
We are trying to solve for the system $Ax = b$ where $A$ is an $n$ x $m$ matrix and $n > m$. If $n = m$, then we could just find the matrix inverse.
Instead, we find an $Ax$ such that we minimize $\|Ax-b\|$.

In [4]:
b = np.random.randint(10, size = (3, 1))
x = np.matmul(np.matmul(np.linalg.inv(r),np.transpose(q)), b)
Ax = np.matmul(A, x)
print('solution vector: \n', x, '\n')
print('b: \n', b, '\n')
print('Ax: \n', Ax, '\n')


solution vector: 
 [[ 0.67741935]
 [-0.37096774]
 [ 0.38709677]] 

b: 
 [[2]
 [0]
 [4]] 

Ax: 
 [[2.00000000e+00]
 [6.66133815e-16]
 [4.00000000e+00]] 



As you can see from the above code, we generate a random $b$ vector and use the random $A, Q, R$ values from the previous QR decomposition example. $Ax$ should give a close approximation to $b$.

# 1.3.3 Linear Regression
Linear regression seeks to find an affine function to fit a data set as closely as possible. This is a minimization problem and when looked at in matrix form, is the exact same as the least-squares problem. 