<a href="https://colab.research.google.com/github/aaronyu888/mat-494-notebooks/blob/main/Linear_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Chapter 1.3 Linear Regression


---



# 1.3.1 QR Decomposition
QR factorization takes the general form $A = QR$ where $Q$ is the product of the Gram-Schmidt process, and $R$ is an upper triangular matrix.

In [77]:
import numpy as np

In [97]:
A = np.random.randint(10, size = (3, 3))
q, r = np.linalg.qr(A)
print(A, '\n')
print(q, '\n')
print(r, '\n')

[[2 1 6]
 [3 1 3]
 [2 3 1]] 

[[-0.48507125 -0.14927036 -0.86164044]
 [-0.72760688 -0.47766515  0.49236596]
 [-0.48507125  0.86576808  0.12309149]] 

[[-4.12310563 -2.66789188 -5.57831938]
 [ 0.          1.97036873 -1.46284951]
 [ 0.          0.         -3.56965324]] 



In [121]:
p = (np.matmul(q, r))
print(p, '\n')
print(A)


[[2. 1. 6.]
 [3. 1. 3.]
 [2. 3. 1.]] 

[[2 1 6]
 [3 1 3]
 [2 3 1]]


As you can see from the above code, $Q$ dotted with $R$ gives us back $A$.



# 1.3.2 Least-squares Problems
We are trying to solve for the system $Ax = b$ where $A$ is an $n$ x $m$ matrix and $n > m$. If $n = m$, then we could just find the matrix inverse.
Instead, we find an $Ax$ such that we minimize $\|Ax-b\|$.

In [143]:
b = np.random.randint(10, size = (3, 1))
x = np.matmul(np.matmul(np.linalg.inv(r),np.transpose(q)), b)
Ax = np.matmul(A, x)
print('solution vector: \n', x, '\n')
print('b: \n', b, '\n')
print('Ax: \n', Ax, '\n')


solution vector: 
 [[-0.55172414]
 [ 1.20689655]
 [ 1.48275862]] 

b: 
 [[9]
 [4]
 [4]] 

Ax: 
 [[9.]
 [4.]
 [4.]] 



As you can see from the above code, we generate a random $b$ vector and use the random $A, Q, R$ values from the previous QR decomposition example. $Ax$ should give a close approximation to $b$.

# 1.3.3 Linear Regression
Linear regression seeks to find an affine function to fit a data set as closely as possible. This is a minimization problem and when looked at in matrix form, is the exact same as the least-squares problem. 